version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - docker/check: 
          registry-url: https://index.docker.io/v1/
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Building Docker Image
          command: |
            docker build -t vacunarg:latest .
      - run:
          name: Docker Login
          command: echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - run:
          name: Tagging Docker Image
          command: |
            docker tag vacunarg:latest ${DOCKER_USERNAME}/vacunarg:latest
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push ${DOCKER_USERNAME}/vacunarg:latest
  deploy:
    machine: 
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "22:08:a2:51:fa:e5:04:3d:25:57:70:90:1b:69:12:e4"
      - run:
          name: Deploy Docker Container to Instance
          command: |
            ssh -o "StrictHostKeyChecking=no" ${SSH_USERNAME}@${SSH_HOST} 'docker stop vacunarg || true && docker rm vacunarg || true'
            ssh -o "StrictHostKeyChecking=no" ${SSH_USERNAME}@${SSH_HOST} 'docker pull ${DOCKER_USERNAME}/vacunarg:latest && docker run -d --name vacunarg -p 8081:80 ${DOCKER_USERNAME}/vacunarg:latest'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master