version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:1c:4f:f5:e7:86:71:2a:dd:64:d8:1b:a0:4d:7a:fe"
      - checkout
      - run: 
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Building Docker Image
          command: docker build -t $DOCKER_USER/vacunarg:$CIRCLE_SHA1 .
      - run: 
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKER_USER/vacunarg:$CIRCLE_SHA1
      - run: 
          name: Pull Docker Image on Remote Host
          command: ssh david_mercado@vacunarg.site "docker pull $DOCKER_USER/vacunarg:$CIRCLE_SHA1"
      - run: 
          name: Stop and Remove Old Docker Container if Exists
          command: ssh david_mercado@vacunarg.site "docker stop vacunarg_container || true && docker rm vacunarg_container || true"
      - run: 
          name: Start Docker Container on Remote Host
          command: ssh david_mercado@vacunarg.site "docker run -d --name vacunarg_container -p 8081:80 $DOCKER_USER/vacunarg:$CIRCLE_SHA1"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
