version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3a:81:74:61:3b:6d:2e:e2:e8:42:5a:a7:66:b9:6e:5e"
      - checkout
      - run: 
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Building Docker Image
          command: docker build -t $DOCKER_USER/vacunarg:$CIRCLE_SHA1 .
      - run: 
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKER_USER/vacunarg:$CIRCLE_SHA1
      - run: 
          name: Pull Docker Image on Remote Host
          command: ssh nicolas@20.226.108.27 "docker pull $DOCKER_USER/vacunarg:$CIRCLE_SHA1"
      - run: 
          name: Stop and Remove Old Docker Container if Exists
          command: ssh nicolas@20.226.108.27 "docker stop vacunarg_container || true && docker rm vacunarg_container || true"
      - run: 
          name: Start Docker Container on Remote Host
          command: ssh nicolas@20.226.108.27 "docker run -d --name vacunarg_container -p 8081:80 $DOCKER_USER/vacunarg:$CIRCLE_SHA1"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
